/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "eu-west-2",
  aws_cognito_identity_pool_id:
    "eu-west-2:c1acaad4-9d0c-4151-9ef4-e88520dcdc40",
  aws_cognito_region: "eu-west-2",
  aws_user_pools_id: "eu-west-2_OuXc4ZpsU",
  aws_user_pools_web_client_id: "2ojmkpj241a2jmsd02scen1eck",
  oauth: {
    domain:
      "edumanagesaasda694ea8-da694ea8-dev.auth.eu-west-2.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "http://localhost:3000/",
    redirectSignOut: "http://localhost:3000/",
    responseType: "token",
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: "6",
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_appsync_graphqlEndpoint:
    "https://gj3enzgrgvhufk5imqqbf442ny.appsync-api.eu-west-2.amazonaws.com/graphql",
  aws_appsync_region: "eu-west-2",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_appsync_apiKey: "da2-s3eb3ixtgbbghaerjab7qqeoje",
  aws_cloud_logic_custom: [
    {
      name: "adminUpdateUserAttribute",
      endpoint: "https://ftrdns136f.execute-api.eu-west-2.amazonaws.com/dev",
      region: "eu-west-2",
    },
  ],
};

export default awsmobile;
